/**
 * dsh-morning-paper — pure briefing core.
 *
 * A briefing is COMPUTED from the durable session log, never generated by a
 * model: zero tokens, no hallucination, byte-deterministic for a given input
 * and clock. This module has no `ctx`, no I/O, and no ambient clock, which is
 * what makes the whole product testable offline.
 *
 * The page exists to say what the transcript buries. A chat is a linear list of
 * messages; it does not tell you which files took the churn, where the wall
 * clock went, which single turn ate a third of the spend, what failed and was
 * never retried, or what you asked for an hour ago. Everything here is an
 * aggregation over a window, and nothing here restates a message you can read.
 *
 * Scope rules, because a front page is about "what happened while I was away"
 * AND "what needs me right now":
 *
 * - Window facts (activity, files, timing, money, unresolved) count only events
 *   with `seq > sinceSeq`. The caller owns what "away" means.
 * - Standing facts (pending approvals, the newest turn outcome) fold the WHOLE
 *   log, because an approval asked before you left is still waiting, and a turn
 *   that ended `blocked` an hour ago is still blocked.
 *
 * Fork-inherited events are excluded from the window and named in `notes`:
 * reporting a forked session's inherited prefix as work your agent just did
 * would be a lie, and `readSession` hands us the exact prefix length.
 */

/** Bump when the briefing document shape changes incompatibly. */
export const BRIEFING_VERSION = 2;

/** Same-origin route owned by the host half. */
export const ROUTE_PATH = '/morning-paper';

/** Slash command exposed by the host half. */
export const COMMAND_NAME = 'briefing';

/** Defensive ceiling for one whole session log read. */
export const MAX_LOG_EVENTS = 20000;
/** The newest window this many events large is summarised; older ones are dropped with a note. */
export const MAX_WINDOW_EVENTS = 5000;
/** Ceiling for the action-required list. */
export const MAX_ACTION_ITEMS = 20;
/** Ceiling for the notes list. */
export const MAX_NOTES = 12;
/** Ceiling for the listed files. */
export const MAX_FILES = 10;
/** Ceiling for the grouped failure list. */
export const MAX_FAILURE_GROUPS = 6;
/** Ceiling for the tool histogram and time table. */
export const MAX_TOOLS = 6;
/** Ceiling for the per-turn timeline, newest last. */
export const MAX_TIMELINE_TURNS = 12;
/** Ceiling for the per-turn spend ranking. */
export const MAX_TOP_TURNS = 3;
/** Ceiling for the unresolved-failure list. */
export const MAX_UNRESOLVED = 6;
/** Ceiling for the "you asked" list. */
export const MAX_ASKS = 4;
/** Ceiling for quoted model text. */
export const MAX_QUOTE_CHARS = 240;
/** Ceiling for a quoted shell command. */
export const MAX_COMMAND_CHARS = 90;

/** Tool names whose calls mean "this file was worked on". */
const FILE_TOOLS = new Set(['edit', 'write', 'str_replace_editor', 'multi_edit', 'notebook_edit']);
/** Tool names whose calls are shell commands. */
const SHELL_TOOLS = new Set(['bash', 'pwsh']);

/** Typed failure translated to a narrow HTTP response by the route. */
export class BriefingError extends Error {
  /**
   * @param status - HTTP status the route answers with.
   * @param code - stable machine-readable failure code.
   * @param message - human-readable explanation shown by the client panel.
   */
  constructor(status, code, message) {
    super(message);
    this.status = status;
    this.code = code;
    this.name = 'BriefingError';
  }
}

/** @returns a {@link BriefingError} without an `if` ladder at every call. */
function fail(status, code, message) {
  return new BriefingError(status, code, message);
}

/** @returns a bounded non-empty string field. */
function stringField(value, field) {
  if (typeof value !== 'string' || value.length === 0 || value.length > 256) {
    throw fail(400, 'BAD_REQUEST', `${field} must be a non-empty string`);
  }
  return value;
}

/** @returns a number field or a default when absent/non-finite. */
function num(value, fallback = 0) {
  return typeof value === 'number' && Number.isFinite(value) ? value : fallback;
}

/** @returns non-negative integer arithmetic that cannot produce NaN. */
function safeSum(total, addend) {
  const next = total + addend;
  return Number.isSafeInteger(next) && next >= 0 ? next : total;
}

/** @returns whether a value is a plain record. */
function isRecord(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * Strip C0/C1 control characters from text that came out of a session.
 *
 * Quoted model output and tool output can contain anything, including ANSI
 * escape sequences. A page that renders session content must not forward those:
 * they can move the cursor, clear the screen, or rewrite what the reader saw.
 *
 * @param text - untrusted session text.
 * @returns the text with control characters removed.
 */
function sanitize(text) {
  if (typeof text !== 'string') return '';
  return text.replace(/[\u0000-\u001F\u007F-\u009F]/g, '');
}

/** @returns the value clipped to a bounded length with an ASCII truncation marker. */
function clip(text, limit = MAX_QUOTE_CHARS) {
  const flat = sanitize(text).replace(/\s+/g, ' ').trim();
  return flat.length <= limit ? flat : `${flat.slice(0, limit - 3).trimEnd()}...`;
}

/** @returns text blocks of one message-ish payload joined, or an empty string. */
function messageText(message) {
  if (!isRecord(message)) return '';
  const content = message.content;
  if (!Array.isArray(content)) return '';
  const parts = [];
  for (const block of content) {
    if (isRecord(block) && block.type === 'text' && typeof block.text === 'string') parts.push(block.text);
  }
  return parts.join(' ').replace(/\s+/g, ' ').trim();
}

/** @returns the `turn` number an event belongs to, or null. */
function turnOf(event) {
  const data = event.data;
  return isRecord(data) && typeof data.turn === 'number' && Number.isSafeInteger(data.turn) ? data.turn : null;
}

/**
 * @param data - one `tool/result` payload.
 * @returns the call id it answers, across the shapes the log actually uses.
 *
 * Verified against real logs: `tool/result.message.source.callId` is where the
 * id lives, with the tool-result content block's `toolCallId` as the mirror.
 */
function callIdOf(data) {
  const message = isRecord(data.message) ? data.message : undefined;
  const source = isRecord(message?.source) ? message.source : undefined;
  const firstBlock = Array.isArray(message?.content) && isRecord(message.content[0]) ? message.content[0] : undefined;
  for (const candidate of [source?.callId, firstBlock?.toolCallId, message?.callId, message?.toolCallId, data.callId]) {
    if (typeof candidate === 'string' && candidate.length > 0) return candidate;
  }
  return null;
}

/** @returns the parsed tool arguments, or null when they are not a JSON object. */
function parseArguments(raw) {
  if (typeof raw !== 'string') return null;
  try {
    const parsed = JSON.parse(raw);
    return isRecord(parsed) ? parsed : null;
  } catch {
    return null;
  }
}

/** @returns the file one file-tool call addressed, or null. */
function fileOf(name, args) {
  if (!FILE_TOOLS.has(name) || args === null) return null;
  for (const key of ['file_path', 'path', 'notebook_path', 'filePath']) {
    if (typeof args[key] === 'string' && args[key].length > 0) return clip(args[key], 200);
  }
  return null;
}

/** @returns the shell command of one call's arguments, or null. */
function commandOf(raw) {
  const args = parseArguments(raw);
  if (args === null) return null;
  for (const key of ['command', 'script', 'cmd']) {
    if (typeof args[key] === 'string' && args[key].length > 0) return clip(args[key], MAX_COMMAND_CHARS);
  }
  return null;
}

/**
 * Decode and validate one briefing request.
 * @param params - parsed query parameters.
 * @returns the validated request.
 */
export function decodeBriefingRequest(params) {
  const read = (name) => (typeof params?.get === 'function' ? params.get(name) : undefined);
  const sessionId = stringField(read('sessionId') ?? undefined, 'sessionId');
  const rawSince = read('sinceSeq');
  let sinceSeq = -1;
  if (rawSince !== undefined && rawSince !== null && rawSince !== '') {
    const parsed = Number(rawSince);
    if (!Number.isSafeInteger(parsed) || parsed < 0) {
      throw fail(400, 'BAD_REQUEST', 'sinceSeq must be a non-negative integer');
    }
    sinceSeq = parsed;
  }
  const rawFormat = read('format');
  const format = rawFormat === undefined || rawFormat === null || rawFormat === '' ? 'json' : rawFormat;
  if (format !== 'json' && format !== 'text') {
    throw fail(400, 'BAD_REQUEST', 'format must be "json" or "text"');
  }
  const probe = read('probe') === '1';
  return { sessionId, sinceSeq, format, probe };
}

/**
 * Fold one window of events into everything the page reports.
 *
 * @param window - window events, ascending by seq.
 * @returns the fold.
 */
function foldWindow(window) {
  const fold = {
    turns: { completed: 0, blocked: 0, error: 0, aborted: 0, maxTokens: 0, interrupted: 0, other: 0 },
    newestTurnEnd: null,
    toolCalls: new Map(),
    toolMs: new Map(),
    durations: [],
    toolFailures: 0,
    failures: [],
    failureGroups: new Map(),
    llmRetries: 0,
    compactions: 0,
    presentedFiles: new Set(),
    presentedCount: 0,
    tokenBuckets: { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0 },
    files: new Map(),
    commands: { total: 0, failed: 0 },
    asks: [],
    turnsById: new Map(),
    other: 0,
  };
  const openCalls = new Map();

  /** @returns the mutable timeline row for one turn. */
  const turnRow = (turn, time) => {
    const row = fold.turnsById.get(turn) ?? {
      turn,
      start: time,
      end: null,
      outcome: null,
      steps: 0,
      tools: 0,
      tokens: 0,
    };
    if (time < row.start) row.start = time;
    fold.turnsById.set(turn, row);
    return row;
  };

  for (const event of window) {
    const data = isRecord(event.data) ? event.data : {};
    const time = num(event.time);
    const turn = turnOf(event);
    switch (event.type) {
      case 'turn/start': {
        if (turn !== null) turnRow(turn, time);
        break;
      }
      case 'turn/end': {
        const reason = isRecord(data.reason) ? data.reason : {};
        const kind = typeof reason.kind === 'string' ? reason.kind : 'other';
        if (kind === 'completed') fold.turns.completed += 1;
        else if (kind === 'blocked') fold.turns.blocked += 1;
        else if (kind === 'error') fold.turns.error += 1;
        else if (kind === 'aborted') fold.turns.aborted += 1;
        else if (kind === 'max-tokens') fold.turns.maxTokens += 1;
        else if (kind === 'interrupted') fold.turns.interrupted += 1;
        else fold.turns.other += 1;
        fold.newestTurnEnd = event;
        if (turn !== null) {
          const row = turnRow(turn, time);
          row.end = time;
          row.outcome = kind;
        }
        break;
      }
      case 'step/start': {
        if (turn !== null) turnRow(turn, time).steps += 1;
        break;
      }
      case 'assistant/message': {
        const usage = isRecord(data.usage) ? data.usage : undefined;
        if (usage !== undefined) {
          fold.tokenBuckets.inputTokens = safeSum(fold.tokenBuckets.inputTokens, num(usage.inputTokens));
          fold.tokenBuckets.outputTokens = safeSum(fold.tokenBuckets.outputTokens, num(usage.outputTokens));
          fold.tokenBuckets.cacheReadTokens = safeSum(fold.tokenBuckets.cacheReadTokens, num(usage.cacheReadTokens));
          fold.tokenBuckets.cacheWriteTokens = safeSum(fold.tokenBuckets.cacheWriteTokens, num(usage.cacheWriteTokens));
        }
        if (turn !== null) {
          const spent = usage === undefined
            ? 0
            : num(usage.inputTokens) + num(usage.cacheReadTokens) + num(usage.cacheWriteTokens) + num(usage.outputTokens);
          const row = turnRow(turn, time);
          row.tokens = safeSum(row.tokens, spent);
        }
        break;
      }
      case 'tool/call': {
        const name = typeof data.name === 'string' && data.name.length > 0 ? data.name : 'unknown';
        fold.toolCalls.set(name, (fold.toolCalls.get(name) ?? 0) + 1);
        if (typeof data.callId === 'string') openCalls.set(data.callId, { name, time, arguments: data.arguments });
        const file = fileOf(name, parseArguments(data.arguments));
        if (file !== null) fold.files.set(file, (fold.files.get(file) ?? 0) + 1);
        if (SHELL_TOOLS.has(name)) fold.commands.total += 1;
        break;
      }
      case 'tool/result': {
        const error = isRecord(data.error) ? data.error : undefined;
        const callId = callIdOf(data);
        const call = callId === null ? undefined : openCalls.get(callId);
        if (call !== undefined) {
          const spent = Math.max(0, time - call.time);
          fold.toolMs.set(call.name, (fold.toolMs.get(call.name) ?? 0) + spent);
          fold.durations.push({ tool: call.name, ms: spent, time: call.time });
          if (turn !== null) turnRow(turn, time).tools += 1;
        }
        if (error !== undefined) {
          fold.toolFailures += 1;
          const tool = call?.name ?? 'unknown';
          const code = typeof error.code === 'string' ? error.code : 'UNKNOWN';
          const key = `${tool}/${code}`;
          fold.failureGroups.set(key, (fold.failureGroups.get(key) ?? 0) + 1);
          if (SHELL_TOOLS.has(tool)) fold.commands.failed += 1;
          fold.failures.push({
            time,
            tool,
            code,
            name: typeof error.name === 'string' ? error.name : null,
            command: SHELL_TOOLS.has(tool) ? commandOf(call?.arguments) : null,
          });
        }
        break;
      }
      case 'llm/retry':
      case 'llm/retry-started':
        fold.llmRetries += 1;
        break;
      case 'compaction/start':
        fold.compactions += 1;
        break;
      case 'deliverables/presented': {
        const files = Array.isArray(data.files) ? data.files : [];
        fold.presentedCount += 1;
        for (const file of files) {
          if (isRecord(file) && typeof file.path === 'string' && file.path.length > 0) fold.presentedFiles.add(file.path);
        }
        break;
      }
      case 'user/message': {
        const text = messageText(data);
        const source = isRecord(data.source) ? data.source : undefined;
        // Plugin- and harness-authored messages are not things you asked for.
        if (text.length > 0 && (source === undefined || source.kind === 'user')) {
          fold.asks.push({ time, text: clip(text, 140) });
        }
        break;
      }
      default:
        fold.other += 1;
        break;
    }
  }
  return fold;
}

/**
 * Fold the standing facts that must survive the away window: approvals asked
 * but never decided, and where the log currently stands.
 * @param events - every event in the log, ascending by seq.
 * @returns pending asks and the tail seq.
 */
function foldStanding(events) {
  const asked = new Map();
  const decided = new Set();
  let tailSeq = -1;
  for (const event of events) {
    if (typeof event.seq === 'number' && event.seq > tailSeq) tailSeq = event.seq;
    if (!isRecord(event.data)) continue;
    if (event.type === 'approval/asked' && typeof event.data.id === 'string') {
      asked.set(event.data.id, event);
    } else if (event.type === 'approval/decided' && typeof event.data.id === 'string') {
      decided.add(event.data.id);
    }
  }
  const pending = [];
  for (const [id, event] of asked) {
    if (decided.has(id)) continue;
    const data = event.data;
    pending.push({
      kind: 'approval',
      id,
      toolName: typeof data.toolName === 'string' && data.toolName.length > 0 ? data.toolName : 'unknown',
      reason: typeof data.reason === 'string' && data.reason.length > 0 ? clip(data.reason, 120) : null,
      seq: event.seq,
      time: num(event.time),
    });
  }
  return { pending, tailSeq };
}

/** @returns the newest turn/end event across the whole log, or null. */
function newestTurnEnd(events) {
  let found = null;
  for (const event of events) {
    if (event.type === 'turn/end') found = event;
  }
  return found;
}

/** @returns the newest event at or before `seq`, used to date the away window. */
function eventAtOrBefore(events, seq) {
  let found = null;
  for (const event of events) {
    if (typeof event.seq === 'number' && event.seq <= seq) found = event;
  }
  return found;
}

/** @returns the highest turn number any event in the log mentions, or null. */
function newestTurnNumber(events) {
  let highest = null;
  for (const event of events) {
    const turn = turnOf(event);
    if (turn !== null && (highest === null || turn > highest)) highest = turn;
  }
  return highest;
}

/** @returns the tool name behind one call id within a window, or null. */
function toolNameFor(window, callId) {
  for (const event of window) {
    if (event.type !== 'tool/call' || !isRecord(event.data)) continue;
    if (event.data.callId === callId && typeof event.data.name === 'string') return event.data.name;
  }
  return null;
}

/**
 * Build one briefing document.
 *
 * @param log - `{ session, inheritedEventCount, events }` as `readSession` returns it,
 * plus an optional `title` string the host resolved separately.
 * @param sinceSeq - last seq the caller already saw; `-1` asks for the whole session.
 * @param now - Unix epoch ms; injected so output is deterministic.
 * @param extras - optional live-only facts the durable log cannot carry:
 * `{ pendingQuestions, weather }`.
 * @returns the briefing document.
 */
export function buildBriefing(log, sinceSeq = -1, now = 0, extras = {}) {
  if (!isRecord(log) || !Array.isArray(log.events)) {
    throw fail(500, 'BAD_LOG', 'session log is not readable');
  }
  const session = isRecord(log.session) ? log.session : {};
  if (typeof session.id !== 'string' || session.id.length === 0) {
    throw fail(500, 'BAD_LOG', 'session log carries no identity');
  }
  if (session.origin === 'subagent') {
    throw fail(409, 'SUBAGENT_OWNED', 'a subagent session briefing is owned by its parent session');
  }
  const events = log.events.filter(isRecord);
  if (events.length > MAX_LOG_EVENTS) {
    throw fail(413, 'LOG_TOO_LARGE', `this session has ${String(events.length)} events, above the ${String(MAX_LOG_EVENTS)} the briefing will read`);
  }
  const requested = Number.isSafeInteger(sinceSeq) && sinceSeq >= -1 ? sinceSeq : -1;
  const inheritedEventCount = Number.isSafeInteger(log.inheritedEventCount) && log.inheritedEventCount > 0
    ? log.inheritedEventCount
    : 0;

  const notes = [];
  const standing = foldStanding(events);
  if (requested >= 0 && requested > standing.tailSeq) {
    throw fail(409, 'MARKER_AHEAD', 'the reading marker is ahead of this session log; reset it to the current tail');
  }

  const afterMarker = events.filter((event) => typeof event.seq === 'number' && event.seq > requested);
  const inheritedSkipped = afterMarker.filter((event) => event.seq < inheritedEventCount).length;
  let window = afterMarker.filter((event) => event.seq >= inheritedEventCount);
  if (inheritedSkipped > 0) {
    notes.push(`${String(inheritedSkipped)} fork-inherited event(s) in this window were excluded: they happened in the session this one was forked from, not here.`);
  }
  if (window.length > MAX_WINDOW_EVENTS) {
    const dropped = window.length - MAX_WINDOW_EVENTS;
    window = window.slice(-MAX_WINDOW_EVENTS);
    notes.push(`${String(dropped)} older event(s) fall outside the summarised window; only the newest ${String(MAX_WINDOW_EVENTS)} were read.`);
  }

  const fold = foldWindow(window);
  const windowFirst = window[0];
  const windowLast = window[window.length - 1];
  const markerEvent = requested >= 0 ? eventAtOrBefore(events, requested) : null;
  const fromTime = markerEvent !== null && typeof markerEvent.time === 'number'
    ? markerEvent.time
    : num(session.createdAt, num(windowFirst?.time, now));
  const toTime = windowLast !== undefined && typeof windowLast.time === 'number' ? windowLast.time : fromTime;
  const windowMs = Math.max(0, toTime - fromTime);
  const awayMs = Math.max(0, num(now) - fromTime);

  // Action required: standing pending approvals first (oldest ask is the most
  // urgent), then a turn that ended blocked with nothing else to click.
  const actionRequired = [];
  const pending = [...standing.pending].sort((left, right) => left.seq - right.seq);
  for (const item of pending) {
    if (actionRequired.length >= MAX_ACTION_ITEMS) break;
    actionRequired.push({ ...item, ageMs: Math.max(0, num(now) - item.time) });
  }
  for (const question of Array.isArray(extras.pendingQuestions) ? extras.pendingQuestions : []) {
    if (actionRequired.length >= MAX_ACTION_ITEMS) break;
    if (!isRecord(question)) continue;
    actionRequired.push({
      kind: 'question',
      id: typeof question.id === 'string' ? question.id : 'pending',
      question: clip(typeof question.question === 'string' ? question.question : 'a question is waiting for you', 120),
      ageMs: Math.max(0, num(now) - num(question.time, num(now))),
    });
  }
  const newestEnd = newestTurnEnd(events);
  const newestEndReason = isRecord(newestEnd?.data?.reason) ? newestEnd.data.reason : {};
  const newestEndKind = typeof newestEndReason.kind === 'string' ? newestEndReason.kind : null;
  if (newestEndKind === 'blocked' && pending.length === 0 && actionRequired.length < MAX_ACTION_ITEMS) {
    actionRequired.push({
      kind: 'blocked',
      turn: turnOf(newestEnd),
      seq: newestEnd.seq,
      ageMs: Math.max(0, num(now) - num(newestEnd.time, num(now))),
    });
  }

  // Lead: the outcome of the newest finished turn in the window, or plain
  // activity, or a deliberately dull page. Deliberately no quoted reply and no
  // tool histogram: the transcript already has those, and a briefing that
  // restates the chat is worth nothing.
  const leadEnd = fold.newestTurnEnd;
  let lead;
  if (window.length === 0) {
    lead = { kind: 'quiet' };
  } else if (leadEnd !== null && isRecord(leadEnd.data)) {
    const reason = isRecord(leadEnd.data.reason) ? leadEnd.data.reason : {};
    const kind = typeof reason.kind === 'string' ? reason.kind : 'other';
    lead = {
      kind,
      turn: turnOf(leadEnd),
      seq: leadEnd.seq,
      time: num(leadEnd.time),
      error: kind === 'error' && isRecord(reason.error)
        ? { code: typeof reason.error.code === 'string' ? reason.error.code : 'UNKNOWN', message: clip(typeof reason.error.message === 'string' ? reason.error.message : '') }
        : null,
      cancelReason: kind === 'aborted' && isRecord(reason.reason) && typeof reason.reason.kind === 'string' ? reason.reason.kind : null,
    };
  } else {
    lead = { kind: 'activity', turn: turnOf(windowLast) ?? null, seq: windowLast?.seq ?? null, time: num(windowLast?.time) };
  }

  // Per-turn timeline: the shape of the window, which no single message shows.
  const timeline = [...fold.turnsById.values()]
    .sort((left, right) => left.turn - right.turn)
    .slice(-MAX_TIMELINE_TURNS)
    .map((row) => {
      const end = row.end ?? toTime;
      return {
        turn: row.turn,
        start: row.start,
        end: row.end,
        durationMs: Math.max(0, end - row.start),
        steps: row.steps,
        tools: row.tools,
        tokens: row.tokens,
        outcome: row.outcome,
      };
    });

  // Where the wall clock went. Tool time is measured from call to result;
  // everything else in the window was the model working, which is the number
  // nobody ever sees.
  const toolMs = [...fold.toolMs.values()].reduce((total, spent) => safeSum(total, spent), 0);
  const tools = [...fold.toolCalls.keys()]
    .map((tool) => ({ tool, calls: fold.toolCalls.get(tool), ms: fold.toolMs.get(tool) ?? 0 }))
    .sort((left, right) => (right.ms - left.ms) || (right.calls - left.calls) || left.tool.localeCompare(right.tool))
    .slice(0, MAX_TOOLS)
    .map((row) => ({ ...row, share: toolMs > 0 ? Math.round((row.ms / toolMs) * 1000) / 10 : 0 }));
  const longest = fold.durations.reduce((best, row) => (row.ms > best.ms ? row : best), { tool: null, ms: 0, time: 0 });

  const billedInput = fold.tokenBuckets.inputTokens + fold.tokenBuckets.cacheReadTokens + fold.tokenBuckets.cacheWriteTokens;
  const totalTokens = safeSum(billedInput, fold.tokenBuckets.outputTokens);
  const topTurns = [...fold.turnsById.values()]
    .filter((row) => row.tokens > 0)
    .sort((left, right) => right.tokens - left.tokens)
    .slice(0, MAX_TOP_TURNS)
    .map((row) => ({
      turn: row.turn,
      tokens: row.tokens,
      share: totalTokens > 0 ? Math.round((row.tokens / totalTokens) * 100) : 0,
      tools: row.tools,
      outcome: row.outcome,
    }));

  // Failures nobody came back to: a later success of the same tool means it was
  // handled; no later success means it is still sitting there.
  const successesByTool = new Map();
  for (const event of window) {
    if (event.type !== 'tool/result' || !isRecord(event.data)) continue;
    if (isRecord(event.data.error)) continue;
    const callId = callIdOf(event.data);
    if (callId === null) continue;
    const tool = toolNameFor(window, callId);
    if (tool === null) continue;
    const times = successesByTool.get(tool) ?? [];
    times.push(num(event.time));
    successesByTool.set(tool, times);
  }
  const unresolved = fold.failures
    .filter((failure) => !(successesByTool.get(failure.tool) ?? []).some((time) => time > failure.time))
    .slice(-MAX_UNRESOLVED);

  const files = [...fold.files.entries()]
    .sort((left, right) => (right[1] - left[1]) || left[0].localeCompare(right[0]))
    .slice(0, MAX_FILES)
    .map(([path, edits]) => ({ path, edits }));

  const weather = isRecord(extras.weather) ? extras.weather : null;
  if (weather === null) {
    notes.push('No live session was attached, so context pressure is not reported for this briefing.');
  }

  const failureGroups = [...fold.failureGroups.entries()]
    .sort((left, right) => (right[1] - left[1]) || left[0].localeCompare(right[0]))
    .slice(0, MAX_FAILURE_GROUPS)
    .map(([failure, count]) => ({ failure, count }));

  return {
    version: BRIEFING_VERSION,
    sessionId: session.id,
    title: typeof log.title === 'string' && log.title.length > 0
      ? clip(log.title, 120)
      : (typeof session.cwd === 'string' && session.cwd.length > 0 ? clip(session.cwd, 200) : null),
    isFork: inheritedEventCount > 0 || session.isSeeded === true,
    window: {
      sinceSeq: requested,
      throughSeq: standing.tailSeq,
      fromTime,
      toTime,
      awayMs,
      windowMs,
      events: window.length,
      inheritedEventCount,
    },
    masthead: {
      awayMs,
      events: window.length,
      turn: newestTurnNumber(events),
      actionCount: actionRequired.length,
      turns: fold.turnsById.size,
    },
    actionRequired,
    lead,
    turns: fold.turns,
    timeline,
    files: { touched: fold.files.size, listed: files },
    commands: { ...fold.commands },
    timing: {
      windowMs,
      toolMs,
      modelMs: Math.max(0, windowMs - toolMs),
      toolShare: windowMs > 0 ? Math.round((toolMs / windowMs) * 1000) / 10 : null,
      tools,
      longest: { tool: longest.tool, ms: longest.ms, time: longest.time },
    },
    corrections: {
      toolFailures: fold.toolFailures,
      failureGroups,
      llmRetries: fold.llmRetries,
      compactions: fold.compactions,
    },
    business: {
      inputTokens: fold.tokenBuckets.inputTokens,
      outputTokens: fold.tokenBuckets.outputTokens,
      cacheReadTokens: fold.tokenBuckets.cacheReadTokens,
      cacheWriteTokens: fold.tokenBuckets.cacheWriteTokens,
      billedInputTokens: billedInput,
      totalTokens,
      cacheHitPercent: billedInput > 0 ? Math.round((fold.tokenBuckets.cacheReadTokens / billedInput) * 1000) / 10 : null,
      userMessages: fold.asks.length,
      toolCalls: [...fold.toolCalls.values()].reduce((total, count) => safeSum(total, count), 0),
      presentEvents: fold.presentedCount,
      files: [...fold.presentedFiles].map((path) => clip(path, 200)).sort().slice(0, MAX_FILES),
      filesTruncated: Math.max(0, fold.presentedFiles.size - MAX_FILES),
      topTurns,
    },
    unresolved,
    asks: fold.asks.slice(-MAX_ASKS),
    weather,
    notes: notes.slice(0, MAX_NOTES),
  };
}

/**
 * Render a briefing as plain text, for the `/briefing` command and for
 * `format=text`. Structural characters are ASCII; quoted session content passes
 * through sanitized but otherwise verbatim.
 *
 * @param briefing - a document from {@link buildBriefing}.
 * @returns the front page as text.
 */
export function renderBriefingText(briefing) {
  const lines = [];
  const rule = '='.repeat(76);
  const dash = '-'.repeat(76);
  const bar = (share, width = 16) => {
    const filled = Math.max(1, Math.round(((share ?? 0) / 100) * width));
    return `${'#'.repeat(filled)}${'.'.repeat(width - filled)}`;
  };
  const leadSentenceOf = () => {
    const lead = briefing.lead;
    switch (lead.kind) {
      case 'completed': return `Turn ${String(lead.turn)} completed.`;
      case 'blocked': return `Turn ${String(lead.turn)} ended blocked - the agent is waiting on you.`;
      case 'error': {
        const code = lead.error?.code ?? 'UNKNOWN';
        const message = lead.error?.message ?? '';
        return `Turn ${String(lead.turn)} failed (${code})${message.length > 0 ? `: ${message}` : ''}`;
      }
      case 'interrupted': return `Turn ${String(lead.turn)} was cut off by a restart; the events before the crash are intact.`;
      case 'max-tokens': return `Turn ${String(lead.turn)} hit the output-token ceiling.`;
      case 'aborted': return `Turn ${String(lead.turn)} was cancelled${lead.cancelReason === null || lead.cancelReason === undefined ? '' : ` (${lead.cancelReason})`}.`;
      case 'activity': return 'Work was still in progress when this briefing was written; no turn has ended in this window.';
      case 'quiet': return 'Nothing happened while you were out.';
      default: return `Turn ${String(lead.turn)} ended (${String(lead.kind)}).`;
    }
  };

  lines.push(rule);
  lines.push(`THE MORNING PAPER - ${briefing.title ?? briefing.sessionId}`);
  const masthead = [
    briefing.window.sinceSeq === -1 ? 'whole session' : `away ${formatDuration(briefing.masthead.awayMs)}`,
    `${String(briefing.masthead.events)} event(s)`,
    `${formatDuration(briefing.window.windowMs)} of wall clock`,
    briefing.masthead.turn === null ? null : `turn ${String(briefing.masthead.turn)}`,
    `${String(briefing.masthead.actionCount)} action(s) required`,
  ].filter((part) => part !== null);
  lines.push(masthead.join(' | '));
  lines.push(rule);

  if (briefing.actionRequired.length > 0) {
    lines.push('');
    lines.push(`ACTION REQUIRED (${String(briefing.actionRequired.length)})`);
    for (const item of briefing.actionRequired) {
      if (item.kind === 'approval') {
        const reason = item.reason === null ? '' : ` - "${item.reason}"`;
        lines.push(`  ! approval for ${item.toolName}${reason} (${formatDuration(item.ageMs)} ago)`);
      } else if (item.kind === 'question') {
        lines.push(`  ! question: ${item.question} (${formatDuration(item.ageMs)} ago)`);
      } else {
        lines.push(`  ! turn ${String(item.turn)} ended blocked (${formatDuration(item.ageMs)} ago)`);
      }
    }
  }

  lines.push('');
  lines.push(briefing.lead.kind === 'quiet' ? 'Nothing happened while you were out.' : `LEAD: ${leadSentenceOf()}`);

  const t = briefing.turns;
  lines.push('');
  lines.push('WHAT IT DID');
  lines.push(`  ${String(briefing.masthead.turns)} turn(s): ${String(t.completed)} finished, ${String(t.blocked)} blocked, ${String(t.error)} failed, ${String(t.aborted)} cancelled, ${String(t.interrupted)} interrupted`);
  lines.push(`  ${String(briefing.business.toolCalls)} tool call(s), ${String(briefing.files.touched)} file(s) touched, ${String(briefing.commands.total)} command(s) run (${String(briefing.commands.failed)} failed)`);

  if (briefing.timeline.length > 0) {
    lines.push('');
    lines.push('TURNS');
    lines.push('  turn   took    steps  tools        tokens  outcome');
    for (const row of briefing.timeline) {
      lines.push(`  ${String(row.turn).padStart(4)}   ${formatDuration(row.durationMs).padEnd(6)} ${String(row.steps).padStart(5)}  ${String(row.tools).padStart(5)}  ${row.tokens.toLocaleString('en-US').padStart(12)}  ${row.outcome ?? 'open'}`);
    }
  }

  if (briefing.files.listed.length > 0) {
    lines.push('');
    lines.push(`FILES (${String(briefing.files.touched)} touched)`);
    for (const file of briefing.files.listed) lines.push(`  ${String(file.edits).padStart(3)}x ${file.path}`);
    const hidden = briefing.files.touched - briefing.files.listed.length;
    if (hidden > 0) lines.push(`  ... and ${String(hidden)} more file(s)`);
  }

  if (briefing.timing.tools.length > 0) {
    lines.push('');
    lines.push('WHERE THE TIME WENT');
    for (const row of briefing.timing.tools) {
      lines.push(`  ${bar(row.share)} ${String(row.share).padStart(5)}%  ${row.tool.padEnd(14)} ${formatDuration(row.ms).padEnd(6)} (${String(row.calls)} calls)`);
    }
    if (briefing.timing.longest.tool !== null) {
      lines.push(`  longest single call: ${briefing.timing.longest.tool} ${formatDuration(briefing.timing.longest.ms)}`);
    }
    if (briefing.timing.toolShare !== null) {
      lines.push(`  tool execution was ${String(briefing.timing.toolShare)}% of the window; the rest was model time`);
    }
  }

  if (briefing.business.topTurns.length > 0) {
    lines.push('');
    lines.push('WHERE THE MONEY WENT');
    for (const row of briefing.business.topTurns) {
      lines.push(`  turn ${String(row.turn).padStart(3)}  ${row.tokens.toLocaleString('en-US').padStart(12)} tokens  ${String(row.share).padStart(3)}% of the window  ${String(row.tools)} tools  ${row.outcome ?? 'open'}`);
    }
  }

  lines.push('');
  lines.push('BUSINESS');
  const pieces = [`${briefing.business.totalTokens.toLocaleString('en-US')} tokens`];
  if (briefing.business.cacheHitPercent !== null) pieces.push(`cache hit ${String(briefing.business.cacheHitPercent)}%`);
  if (briefing.business.userMessages > 0) pieces.push(`${String(briefing.business.userMessages)} message(s) from you`);
  lines.push(`  ${pieces.join(' | ')}`);
  if (briefing.business.files.length > 0) lines.push('  delivered:');
  for (const file of briefing.business.files) lines.push(`  - ${file}`);
  if (briefing.business.filesTruncated > 0) lines.push(`  ... and ${String(briefing.business.filesTruncated)} more`);

  const failures = briefing.corrections;
  if (failures.toolFailures > 0 || failures.llmRetries > 0 || failures.compactions > 0) {
    lines.push('');
    lines.push('CORRECTIONS');
    if (failures.toolFailures > 0) {
      const groups = failures.failureGroups.map((group) => `${group.failure} x${String(group.count)}`).join(', ');
      lines.push(`  ${String(failures.toolFailures)} tool failure(s)${groups.length > 0 ? `: ${groups}` : ''}`);
    }
    if (failures.llmRetries > 0) lines.push(`  ${String(failures.llmRetries)} model retry(ies)`);
    if (failures.compactions > 0) lines.push(`  ${String(failures.compactions)} compaction(s)`);
  }

  if (briefing.unresolved.length > 0) {
    lines.push('');
    lines.push(`UNRESOLVED (${String(briefing.unresolved.length)})`);
    for (const item of briefing.unresolved) {
      const when = new Date(item.time).toISOString().slice(11, 16);
      const what = item.command === null ? '' : `  "${item.command}"`;
      lines.push(`  ${when}  ${item.tool} failed: ${item.code}${what}  (never retried)`);
    }
  }

  if (briefing.asks.length > 0) {
    lines.push('');
    lines.push('YOU ASKED');
    for (const ask of briefing.asks) lines.push(`  - ${ask.text}`);
  }

  lines.push('');
  lines.push('WEATHER');
  if (briefing.weather === null) {
    lines.push('  context pressure unavailable (no live session)');
  } else {
    const windowTokens = briefing.weather.contextWindow;
    const percent = briefing.weather.percent;
    // A configured ceiling is an assumption, so it is labelled wherever shown.
    const source = briefing.weather.source === 'config' ? ' [ceiling from plugin config, not declared by the model]' : '';
    lines.push(
      windowTokens === null || percent === null
        ? `  context ${briefing.weather.contextTokens.toLocaleString('en-US')} tokens (limit unknown)`
        : `  context ${briefing.weather.contextTokens.toLocaleString('en-US')}/${windowTokens.toLocaleString('en-US')} (${String(percent)}%)${source}`,
    );
  }

  if (briefing.notes.length > 0) {
    lines.push('');
    lines.push('NOTES');
    for (const note of briefing.notes) lines.push(`  - ${note}`);
  }
  lines.push('');
  lines.push(dash);
  lines.push(`window: seq ${String(briefing.window.sinceSeq)}..${String(briefing.window.throughSeq)} | briefing v${String(briefing.version)}`);
  return lines.join('\n');
}

/**
 * @param ms - a duration in milliseconds.
 * @returns a compact human duration.
 */
export function formatDuration(ms) {
  const total = Math.max(0, Math.round(num(ms) / 1000));
  if (total < 60) return `${String(total)}s`;
  const minutes = Math.floor(total / 60);
  if (minutes < 60) return `${String(minutes)}m`;
  const hours = Math.floor(minutes / 60);
  const remMinutes = minutes % 60;
  if (hours < 24) return remMinutes === 0 ? `${String(hours)}h` : `${String(hours)}h ${String(remMinutes)}m`;
  const days = Math.floor(hours / 24);
  const remHours = hours % 24;
  return remHours === 0 ? `${String(days)}d` : `${String(days)}d ${String(remHours)}h`;
}

export {
  callIdOf,
  clip,
  commandOf,
  eventAtOrBefore,
  fileOf,
  foldStanding,
  foldWindow,
  messageText,
  newestTurnEnd,
  newestTurnNumber,
  parseArguments,
  sanitize,
};
